


CREATE TABLE IF NOT EXISTS doctor (
  Id serial ,  Code varchar(10) NOT NULL,
  Name_Deg varchar(300) NOT NULL,
  Clinic_Address varchar(500) NOT NULL,
  Clinic_City varchar(50) NOT NULL,
  Clinic_Pin int NOT NULL,
  Clinic_Number varchar(15) NOT NULL,
  Mobile_number varchar(15) NOT NULL,
  Email varchar(100) NOT NULL,
  REMIND varchar(15) NOT NULL,
  Commission double precision NOT NULL,
  PRIMARY KEY (Id)
); 

--
-- Dumping data for table `doctor`
--

INSERT INTO doctor (Id, Code, Name_Deg, Clinic_Address, Clinic_City, Clinic_Pin, Clinic_Number, Mobile_number, Email, REMIND, Commission) VALUES
(1, 'PAK', 'DR.PAKNIKAR', '', '', 0, '', '', '', '', 0),
(2, 'NEA', 'DR.NEHA DESAI', '', '', 0, '', '', '', '', 0),
(3, 'NAC', 'DR.NACHANKAR', '', '', 0, '', '', '', '', 0),
(4, 'LIL', 'LILAVATI  HOSPITAL', '', '', 0, '', '', '', '', 0),
(5, 'PRV', 'DR.PRAVEEN KUMAR', '', '', 0, '', '', '', '', 0),
(6, 'GOV', 'DR.HEMANT GOVARI', '', '', 0, '', '', '', '', 0),
(7, 'ICH', 'ISHWAR CHILDREN NURSING HOME', 'A', 'A', 0, '11111', '1', 'UO', '1', 0),
(8, 'AME', 'DR. AMEY  DESHPANDE', '', '', 0, '', '', '', '', 0),
(9, 'RUP', 'DR.RUCHITA PATIL.', '', '', 0, '', '', '', '', 0),
(10, 'MUN', 'MUNCIPAL  HOSPITAL', '', '', 0, '', '', '', '', 0),
(11, 'NEW', 'NEW  PRAVIN  HOSPITAL', '', '', 0, '', '', '', '', 0),
(12, 'PAN', 'DR.PANCHAL', '', '', 0, '', '', '', '', 0),
(13, 'TEI', 'DR.SHARAD TELTUMBADE.', '', '', 0, '', '', '', '', 0),
(14, 'SIO', 'SION HOSPITAL', '', '', 0, '', '', '', '', 0),
(15, 'RKD', 'DR.R.K.DALAL.', '', '', 0, '', '', '', '', 0),
(16, 'MAD', 'DR.VINOD MADAVI', '', '', 0, '', '', '', '', 0),
(17, 'MAL', 'DR.MALTI KULKARNI', '', '', 0, '', '', '', '', 0),
(18, 'MHA', 'DR.SANJAY MHATRE B.H.M.S.', '', '', 0, '11111', '', '', '', 0),
(19, 'AGA', 'DR.SALIL  AGARWAL', '', '', 0, '', '', '', '', 0),
(20, 'FAR', 'DR.FARUK.', '', '', 0, '', '', '', '', 0),
(21, 'NSH', 'DR.NADEEM SHAIKH. B.H.MS.', 'koliwada', 'koliwada', 0, '11111', '', '', '', 0),
(22, 'LES', 'DR.LESLIE GONSALVES.', '', '', 0, '', '', '', '', 0),
(23, 'PNI', 'DR.PRATIBHA.T.NIJAI. M.B.B.S.D.G.O', 'NIRMAL', '', 0, '11111', '', '', '', 0),
(24, 'SAP', 'DR.SUNIL APOTIKAR', '', '', 0, '', '', '', '', 0),
(25, 'GAL', 'DR.SATYANDRA GALVANKAR.', '', '', 0, '', '', '', '', 0),
(26, 'SUB', 'DR.SUBODH PANDIT.', '', '', 0, '', '', '', '', 0),
(27, 'PRP', 'DR.PRASHEEL PATIL', '', '', 0, '', '', '', '', 0),
(28, 'PIL', 'DR.PILLAI.', '', '', 0, '', '', '', '', 0),
(29, 'GOE', 'GR. VIKRANT  GOEL', '', '', 0, '', '', '', '', 0),
(30, 'HDP', 'DR.H.D.PATIL', '', '', 0, '', '', '', '', 0),
(31, 'KAP', 'DR.KAPIL PATIL.', '', '', 0, '', '', '', '', 0),
(32, 'PHA', 'DR.PHADKE.', '', '', 0, '', '', '', '', 0),
(33, 'DRP', 'DR.RUPAL SHAH', '', '', 0, '', '', '', '', 0),
(34, 'NRH', 'NAIR HOSPITAL', '', '', 0, '', '', '', '', 0),
(35, 'SLF', 'SELF', '', '', 0, '', '', 'YERT', '', 0),
(36, 'PAL', 'DR.PALASKAR.', '', '', 0, '', '', '', '', 0),
(37, 'DSP', 'DR.SAMPADA PATIL', '', '', 0, '', '', '', '', 0),
(38, 'PAR', 'DR.PARVATKAR', '', '', 0, '', '', '', '', 0),
(39, 'TNJ', 'DR.T.NIJAI M.B.B.S.', '', '', 0, '11111', '', '', '', 0),
(40, 'NAB', 'DR.KIRAN NABAR', '', '', 0, '', '', '', '', 0),
(41, 'DRV', 'DR.VALINJKAR', '', '', 0, '', '', '', '', 0),
(42, 'VSH', 'DR. VIJAY SHIRISHKAR   [M.D., D.G.O.]', 'NAVJEEVAN HOSPITAL', 'VASAI(W)', 456, '344054', '98201 34251', 'TDY', '', 10),
(43, 'HDP', 'DR. H. D. PATIL     [M.B.B.S.]', 'NEW MUNICIPAL MARKET', 'VASAI', 454, '45645', '1', 'UIO', '', 0),
(44, 'SSJ', 'DR. S. S. JAIN  [M. F. A. M. (BOM)]', 'SHRI PARAS CLINIC', 'VASAI', 54, '564', '1', 'RTY', '', 0),
(45, 'YAS', 'DR. YASMEEN MEMON  [B.U.M.S. (PUNE)]', 'KOLIWADA', 'VASAI', 44, '1232', '1', 'DFTTFRY', '', 0),
(46, 'MBC', 'DR. M. B. CEREJO  [M.B.B.S]', 'MARY-VILLE', 'VASAI', 4564, '326188', '1', 'O', '', 0),
(47, 'NSG', 'DR. N. S. GALVANKAR [M.B.B.S. (BOM)]', 'SANKARBABA GAVANKAR Rd.', 'VASAI', 56, '645', '1', 'UYO', '', 0),
(48, 'VDP', 'DR. VIJAY PHADKE  [M.D. (BOM)]', 'GURUKRIPA CLINIC', 'VASAI', 45, '325071', '1', 'RTY', '', 0),
(49, 'KHR', 'DR. KHARWADKAR [M.B.B.S. (BOM)]', 'PRAVIN HOSPITAL', 'VASAI', 56, '322464', '1', 'OUI', '', 0),
(50, 'SSA', 'DR. S. S. ANAKAL  [M.B.B.S]', 'MUNICIPAL HOSPITAL', 'VASAI', 456, '322120', '1', 'RTY', '', 0),
(51, 'JVL', 'DR. JAYA VALAVALKAR [M.F.A.M. (BOM)]', 'MHATRE NIWAS, ROOM NO. 1', 'VASAI', 545654, '6454', '1', 'O', '', 0),
(52, 'LFG', 'DR. LESLIE GONSALVES [M.B.B.S. (BOM)]', 'HOLI', 'VASAI', 6456, '324024', '1', 'UYOI', '', 0),
(53, 'BJC', 'DR. B.J.CHOUDHARY  [M.B.B.S.(BOM)]', 'HOLI BAZAAR', 'VASAI', 514, '4564', '1', 'UO', '', 0),
(54, 'AHA', 'DR. A. H. AZMI   [B.U.M.S(PUNE)]', 'KOLIWADA', 'VASAI', 4514534, '64', '1', 'UO', '', 0),
(55, 'PKM', 'DR. P.K.MEHTA.', '', '', 0, '', '', '', '', 0),
(56, 'AMM', 'DR. AMITA MARATHE   [M.D., D.G.O.]', 'CHAITANYA NURSING HOME', 'VASAI', 45, '326220', '1', 'O', '', 20),
(57, 'ARS', 'DR. A. R. SHAIKH  [B. U. M. S. (PUNE)]', '5, MUTTON MARKET', 'VASAI', 45, '323038', '1', 'UI', '', 0),
(58, 'SLF', 'SELF', '', '', 45654, '', '', 'YERT', '', 0),
(59, 'JDK', 'DR. J.D.KOKAL  [M.B.B.S.]', 'AZAD ROAD', 'VASAI', 545, '322550 / 326017', '1', 'IO', '', 0),
(60, 'SGB', 'DR. S. G. BORKAR [M. D.(MED)]', 'NAVJEEVAN HOSPITAL', 'VASAI', 64, '344054', '1', 'YET', '', 0),
(61, 'PAT', 'DR. PRADEEP PATHAK  [B.A.M.S.]', 'PACHU BANDAR', 'VASAI', 5644, '6', '1', 'TUI', '', 0),
(62, 'SNG', 'DR. Mrs. SHAILAJA SHIRISHKAR [M.B.B.S.]', '17, SHREEKRISHNA HSG COMPLEX', 'VASAI', 456, '342885', '9624 304945', 'RT', '', 0),
(63, 'ICH', 'ISHWAR CHILDREN NURSING HOME', 'A', 'VASAI', 45, '43', '1', 'UO', '', 0),
(64, 'RAM', 'DR. RAMAKANT DESAI  [M. D.]', 'DR. DESAI''S CHILDREN HOSP.', 'VASAI', 56, '334844', '1', 'Y', '', 0),
(65, 'HSM', 'DR. HEMANT SAMEL [M.D., D.C.H.]', 'NEW ASHWINI HOSPITAL', 'VASAI', 54, '402017 / 402017', '1', 'UO', '', 0),
(66, 'HRP', 'DR. HARSHAD PATIL', 'AGASHI', 'VASAI', 54, '64', '1', 'UO', '', 0),
(67, 'PAK', 'DR. PRAKASH PAKNIKAR [M.D.(Med.)]', 'VASAI STATION', 'VASAI', 44, '64', '1', 'UOI', '', 0),
(68, 'NMK', 'DR. NILIMA KULKARNI [M.D.,D.G.O]', 'SIDDHAKALA NURSING HOME', 'VASAI', 654, '566', '1', 'UY', '', 0),
(69, 'PRP', 'DR. PRASHEEL PATIL [M.D.,(Med)]', 'BANGLI HOSPITAL', 'VASAI', 456, '564', '1', 'YTUI', '', 0),
(70, 'SHG', 'DR. SHEELA GALVANKAR [ M.B.B.S]', 'PARNAKA', 'VASAI', 44, '64', '1', 'RTY', '', 0),
(71, 'SGV', 'DR. SANDEEP GAVANKAR [M.D., D.G.O]', 'SUSHILA NURSING HOME', 'VASAI', 456, '564', '1', 'RTY', '', 0),
(72, 'SHN', 'DR. SHRIKRISHNA SHINDAGI [M.S.]', 'D''SOUZA NURSING HOME', 'VASAI', 4, '64', '1', 'Y', '', 0),
(73, 'BMF', 'DR. B. M. FADIA [M.D.]', 'VASAI ROAD', 'GHFG', 54, '456', '1', 'UIO', '', 0),
(74, 'ARN', 'DR. A. R. NERKAR [M.S.]', 'PRAVIN HOSPITAL', 'VASAI', 4554, '645', '1', 'OUI', '', 0),
(75, 'GOK', 'DR. GOKARN', 'VIKAS CHILDREN NURSING HOME', 'VASAI', 454, '64', '1', 'U', '', 50),
(76, 'GBK', 'DR. G. B. KALE [M.S.(ORTHO)]', 'KALE HOSPITAL', 'VASAI', 4, '64', '1', 'OIUI', '', 0),
(77, 'KIR', 'DR. KIRTIKUMAR JOSHI', 'YUJTY', 'VASAI', 564, '64', '1', 'UYO', '', 0),
(78, 'CSG', 'DR. C. S. GALVANKAR  [M. D., D. G. O.]', 'DH', 'HF', 45, '46464', '1', 'O', '', 0),
(79, 'JSD', 'DR. JOSEPH S. DSOUZA  [M S]', 'DSOUZA NURSING HOME', 'VASAI', 14, '324412 / 324430', '1111111111', 'UIO', '', 0),
(80, 'MAR', 'DR. MANISH  RENGHE', '', '', 4, '', '', 'OUIO', '', 0),
(81, 'PRT', 'DR. PRAVEEN RAUT [M.D.]', 'RAUT''S HOSPITAL', 'VASAI', 456, '564', '', 'RU', '', 0),
(82, 'SMH', 'DR.SANJAY MHATRE B.H.M.S.', '', '', 0, '', '', '', '', 0),
(83, 'TNJ', 'DR.T.NIJAI M.B.B.S.', '', '', 0, '', '', '', '', 0),
(84, 'NDS', 'DR.NADEEM SHAIKH. B.H.MS.', 'koliwada', '', 0, '', '', '', '', 0),
(85, 'ANG', 'DR. ANIL GOYAL [M.B.B.S., D.C.H.]', 'Dr. Goyal''s Children & Gen Hos', 'Evershine City,Gokhivare,', 455, '', '1', 'OUI', '', 0),
(86, 'PTN', 'DR.PRATIBHA.T.NIJAI. M.B.B.S.D.G.O', 'NIRMAL', '', 0, '', '', '', '', 0),
(87, 'JNY', 'DR. J. N. YADAV', 'HJ', 'VASAI', 4, '', '1', 'UIOU', '', 0),
(88, 'BBB', 'FBVX', '', '', 0, '', '', '', '', 0),
(89, 'SAP', 'DR. SUNIL APOTIKAR [M.D. (BOM)]', 'SUSHILA APARTMENT', 'VASAI', 464, '', '9620111111', 'sap@vsnl.com', '', 40),
(90, 'ACD', 'DR. ANTHONY C. DIAS  [B.A.M.S]', 'HOLI BAZAR', 'VASAI', 54687644, '', '', 'acd@vsnl.com', '', 15);

-- --------------------------------------------------------

--
-- Table structure for table `fields`
--


CREATE TABLE IF NOT EXISTS fields (
  Id serial,
  Fieldname varchar(100) NOT NULL,
  MaleMax varchar(30) NOT NULL,
  MaleMin varchar(30) NOT NULL,
  FemaleMax varchar(30) NOT NULL,
  FemaleMin varchar(30) NOT NULL,
  ChildMax varchar(30) NOT NULL,
  ChildMMin varchar(30) NOT NULL,
  Unit varchar(50) NOT NULL,
  Method varchar(300) NOT NULL,
  DefaultValue varchar(50) NOT NULL,
  Summary varchar(10) NOT NULL,
  Chkmethod varchar(10) NOT NULL,
  PRIMARY KEY (Id)
); 

--
-- Dumping data for table `fields`
--

INSERT INTO fields (Id, Fieldname, MaleMax, MaleMin, FemaleMax, FemaleMin, ChildMax, ChildMMin, Unit, Method, DefaultValue, Summary, Chkmethod) VALUES
(1, 'A/G Ratio', '2:01', '1.2 : 1', '', '', '', '', '', '', '', 'TRUE', 'FALSE'),
(2, 'Ab. Eosinophil Count', '440', '40', '', '', '', '', '/cu.mm', '', '', 'TRUE', 'FALSE'),
(3, 'Albumin', '4.8', '3.3', '', '', '', '', 'gm / dL', '', '', 'TRUE', 'TRUE'),
(4, 'Albumin..', '', '', '', '', '', '', '', '', 'Absent', 'TRUE', 'FALSE'),
(5, 'Amoeabae', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(6, 'Amorp. material', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(7, 'Appearance', '', '', '', '', '', '', '', '', 'Clear', 'FALSE', 'FALSE'),
(8, 'Area Of Induration', '', '', '', '', '', '', 'mm', '', '', 'TRUE', 'FALSE'),
(9, 'ASO Titre', '', '', '', '', '', '', '', '', 'Negative', 'FALSE', 'FALSE'),
(10, 'At end of three Active', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(11, 'At end of three Nonmotile', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(12, 'At end of three Sluggish', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(13, 'Bacteria', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(14, 'Baseophils', '1', '0', '1', '0', '1', '0', '%', '', '0', 'TRUE', 'FALSE'),
(15, 'Bile pigment', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(16, 'Bile salt', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(17, 'Bleeding Time', '5', '1', '', '', '', '', 'Minutes - Seconds', '', '', 'TRUE', 'TRUE'),
(18, 'Blood', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(19, 'Blood (Frank )', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(20, 'BLOOD GLUCOSE LEVEL', '', '', '', '', '', '', '', '', ':-', 'FALSE', 'FALSE'),
(21, 'Blood Group', '', '', '', '', '', '', '', '', 'A', 'FALSE', 'FALSE'),
(22, 'Blood Sugar Fasting', '110', '65', '110', '65', '110', '65', 'mg%', '', '', 'TRUE', 'TRUE'),
(23, 'Blood Sugar Fasting/Random', '140', '80', '', '', '', '', 'mg%', 'God-Pod', '', 'TRUE', 'TRUE'),
(24, 'Blood Sugar PP/Random', '140', '0', '140', '0', '140', '0', 'mg%', 'GOD-POD', '', 'TRUE', 'TRUE'),
(25, 'Blood Urea', '40', '20', '40', '20', '40', '20', 'mg%', 'D.A.M.', '', 'TRUE', 'TRUE'),
(26, 'Blood Urea Nitrogen', '20', '10', '20', '10', '20', '10', 'mg%', 'D.A.M', '', 'TRUE', 'TRUE'),
(27, 'C.P.K', '192', '10', '192', '10', '192', '10', 'I.U/L', '', '', 'TRUE', 'FALSE'),
(28, 'Casts', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(29, 'Chemical Examination', '', '', '', '', '', '', '', '', '-', 'FALSE', 'FALSE'),
(30, 'Clot', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(31, 'Clotting Time', '9', '4', '', '', '', '', 'Minutes -Seconds', '', '', 'TRUE', 'TRUE'),
(32, 'Collection Method', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(33, 'Collection Time', '', '', '', '', '', '', 'A.M / P.M', '', '', 'TRUE', 'FALSE'),
(34, 'Colour', '', '', '', '', '', '', '', '', 'Pale yellow', 'FALSE', 'FALSE'),
(35, 'Consistancy', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(36, 'Control Prothrombin Time', '', '', '', '', '', '', 'Seconds', '', '', 'TRUE', 'FALSE'),
(37, 'C-Reactive Protein', '', '', '', '', '', '', '', '', 'Negative', 'FALSE', 'FALSE'),
(38, 'Crystal', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(39, 'Cysts', '', '', '', '', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(40, 'Deposit', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(41, 'DIFFERENTIAL COUNT', '', '', '', '', '', '', '', '', '--', 'FALSE', 'FALSE'),
(42, 'Direct Coombs Test', '', '', '', '', '', '', '', '', 'Negative', 'FALSE', 'FALSE'),
(43, 'E.S.R  1', '15', '0', '15', '0', '15', '0', 'mm at the end of 1Hour', '', '', 'TRUE', 'FALSE'),
(44, 'E.S.R 2', '', '', '', '', '', '', 'mm at the end of 2 hours', '', '', 'TRUE', 'FALSE'),
(45, 'Eosinophils', '6', '1', '6', '1', '6', '1', '%', '', '', 'TRUE', 'FALSE'),
(46, 'Epithelial cells', '3', '2', '5', '2', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(47, 'External Material Including Parasites', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(48, 'Fat', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(49, 'Flagellates', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(50, 'Fructose Test', '', '', '', '', '', '', '', '', 'Positive', 'FALSE', 'FALSE'),
(51, 'G.G.T.P.', '23', '4', '13', '3.5', '', '', 'I.U.', '', '', 'TRUE', 'FALSE'),
(52, 'G6PDH Activity', '18.7', '6.4', '18.7', '6.4', '18.7', '6.4', 'U/gHb', 'kinetic Method', '', 'TRUE', 'TRUE'),
(53, 'Globulin', '3.6', '1.8', '', '', '', '', 'gm /dL', '', '', 'TRUE', 'FALSE'),
(54, 'Glucose', '', '', '', '', '', '', 'mg %', '', '', 'TRUE', 'FALSE'),
(55, 'Grain Stain', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(56, 'GROSS EXAMINATION', '', '', '', '', '', '', '', '', ':-', 'FALSE', 'FALSE'),
(57, 'Haemoglobin', '18', '14', '16', '12', '18', '12', 'gm%', '', '', 'TRUE', 'FALSE'),
(58, 'HIV', '', '', '', '', '', '', '', 'Elisa', 'Negative', 'FALSE', 'TRUE'),
(59, 'Immature Cells', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(60, 'INDICES', '', '', '', '', '', '', '', '', ':-', 'FALSE', 'FALSE'),
(61, 'Indirect Coombs Test', '', '', '', '', '', '', '', '', 'Negative', 'FALSE', 'FALSE'),
(62, 'Ketone', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(63, 'Liquification', '', '', '', '', '', '', '', '', 'Normal', 'FALSE', 'FALSE'),
(64, 'Lymphocyte', '40', '20', '40', '20', '40', '20', '%', '', '', 'TRUE', 'FALSE'),
(65, 'Lymphocytes', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(66, 'Macrophages', '', '', '', '', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(67, 'Mantoux Test', '', '', '', '', '', '', '', '0.1 ml 10 Tu/ 5 Tu P.P.D injected intradermally and test read between 48 to 72 hrs', 'Negative', 'FALSE', 'TRUE'),
(68, 'Mean Cell Count (MCV)', '92', '82', '', '', '', '', 'cumm', '', '', 'TRUE', 'FALSE'),
(69, 'Mean Cell Haemoglobin (MCH)', '32', '27', '', '', '', '', 'pg', '', '', 'TRUE', 'FALSE'),
(70, 'Mean Cell Haemoglobin Concentration(MCHC)', '36', '32', '36', '32', '36', '32', '%', '', '', 'TRUE', 'FALSE'),
(71, 'Microphages', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(72, 'MICROSCOPIC EXAMINATION', '', '', '', '', '', '', '', '', ':-', 'FALSE', 'FALSE'),
(73, 'Monocytes', '10', '2', '10', '2', '10', '2', '%', '', '', 'TRUE', 'FALSE'),
(74, 'Morph. Abnorms Of W.B.C', '', '', '', '', '', '', '', '', 'As Above', 'FALSE', 'FALSE'),
(75, 'Morphology', '', '', '', '', '', '', '', '', 'Normal', 'FALSE', 'FALSE'),
(76, 'Motility within one hour Active', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(77, 'Motility within one hour Nonmobile', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(78, 'Motility within one hour Sluggish', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(79, 'Mucus', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(80, 'Mucus threads', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(81, 'Nature Of Specimen', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(82, 'Occult blood', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(83, 'Other Abnormalities EC', '', '', '', '', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(84, 'Other Abnormalities PC', '', '', '', '', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(85, 'Other Abnormalities RBC', '', '', '', '', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(86, 'Other Cells', '', '', '', '', '', '', '%', '', '', 'TRUE', 'FALSE'),
(87, 'Other Findings', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(88, 'Others abnorms.', '', '', '', '', '', '', '', '', 'Nil', 'FALSE', 'FALSE'),
(89, 'Ova', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(90, 'P. Index', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(91, 'P.C.V', '54', '40', '47', '35', '54', '35', '%', '', '', 'TRUE', 'FALSE'),
(92, 'Parasites', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(93, 'PCV', '47', '35', '', '', '', '', '%', 'Wintrobe', '', 'TRUE', 'TRUE'),
(94, 'pH', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(95, 'Physical  Examination', '', '', '', '', '', '', '', '', '-', 'FALSE', 'FALSE'),
(96, 'Platelet Count', '4,50,000', '1,50,000', '', '', '', '', '/cu.mm', '', '', 'TRUE', 'FALSE'),
(97, 'Platelets', '4,50,000', '1,50,000', '4,50,000', '1,50,000', '4,50,000', '1,50,000', '/cu.mm', '', 'Adequate', 'TRUE', 'FALSE'),
(98, 'Polymorphs', '75', '40', '75', '40', '75', '40', '%', '', '', 'TRUE', 'FALSE'),
(99, 'Precursur Cells', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(100, 'Pregnancy Test', '', '', '', '', '', '', '', 'Elisa', 'Negative', 'FALSE', 'TRUE'),
(101, 'Prostratic', '4', '0', '', '', '', '', 'I.U.', '', '', 'TRUE', 'FALSE'),
(102, 'Protein', '', '', '', '', '', '', 'gm %', '', '', 'TRUE', 'FALSE'),
(103, 'Prothrombin Time', '16', '12', '', '', '', '', 'Seconds', '', '', 'TRUE', 'TRUE'),
(104, 'PTT', '80', '60', '', '', '', '', 'Seconds', '', '', 'TRUE', 'FALSE'),
(105, 'Pus', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(106, 'Pus cells', '3', '2', '', '', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(107, 'Quantity', '', '', '', '', '', '', 'ml', '', '', 'TRUE', 'FALSE'),
(108, 'R.A (Rheumatoid Arthitis) Test', '', '', '', '', '', '', '', 'Qualitative Latex Slide Test', 'Negative', 'TRUE', 'TRUE'),
(109, 'R.B.C Count', '6', '4.5', '5.5', '4', '6', '4', '* 10 ^ 6 cells/cu.mm', '', '', 'TRUE', 'FALSE'),
(110, 'R.B.C. Morphology', '', '', '', '', '', '', '', '', 'Normocytic Normocromic', 'FALSE', 'FALSE'),
(111, 'RBC', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(112, 'Reaction', '', '', '', '', '', '', '', '', 'Acidic', 'FALSE', 'FALSE'),
(113, 'Red blood cells', '', '', '', '', '', '', '/hpf', '', '', 'TRUE', 'FALSE'),
(114, 'Reducing subs', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(115, 'Reticulocyte Count', '2', '0.2', '2', '0.2', '6', '2', '%', '', '', 'TRUE', 'FALSE'),
(116, 'Rh - Antibody Titre', '', '', '', '', '', '', '', '', 'Negative', 'FALSE', 'FALSE'),
(117, 'Rh Factor', '', '', '', '', '', '', '', '', 'Positive', 'FALSE', 'FALSE'),
(118, 'S. Acid Phos.Total', '1.2', '0.9', '', '', '', '', 'I.U', '', '', 'TRUE', 'FALSE'),
(119, 'S.G.O.T.', '40', '5', '', '', '', '', 'Units/Litre', '', '', 'TRUE', 'TRUE'),
(120, 'S.G.P.T.', '35', '5', '', '', '', '', 'Units/Litre', '', '', 'TRUE', 'TRUE'),
(121, 'Salmonella Typhi "A(H)" Antigen', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(122, 'Salmonella Typhi "B(H)" Antigen', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(123, 'Salmonella Typhi "H" Antigen', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(124, 'Salmonella Typhi "O" Antigen', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(125, 'Sediment', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(126, 'Ser. Alkaline Phosphatase', '90', '20', '', '', '221', '93', 'I.U.', '', '', 'TRUE', 'TRUE'),
(127, 'Serum', '', '', '', '', '', '', '', '', 'Clear', 'FALSE', 'FALSE'),
(128, 'Serum  Inorganic Phosphorus', '4.5', '2.5', '', '', '7', '4', 'mg/ dl', '', '', 'TRUE', 'FALSE'),
(129, 'Serum (Total) Cholesterol', '250', '150', '', '', '', '', 'mg%', '', '', 'TRUE', 'TRUE'),
(130, 'SERUM ACID PHOSPHATASE', '', '', '', '', '', '', '', '', '--', 'FALSE', 'FALSE'),
(131, 'Serum Amylase', '50', '9', '50', '9', '50', '9', 'S.C.UNITS', '', '', 'TRUE', 'FALSE'),
(132, 'Serum Australia Antigen (HBsAg)', '', '', '', '', '', '', '', 'Elisa', 'Negative', 'FALSE', 'TRUE'),
(133, 'SERUM BILIRUBIN', '', '', '', '', '', '', '', '', ':-', 'FALSE', 'FALSE'),
(134, 'Serum Bilirubin Direct', '0.5', '0', '', '', '', '', 'mg%', '', '', 'TRUE', 'TRUE'),
(135, 'Serum Bilirubin Indirect', '', '', '', '', '', '', 'mg%', '', '', 'TRUE', 'FALSE'),
(136, 'Serum Bilirubin Total', '1.2', '0.2', '', '', '', '', 'mg%', '', '', 'TRUE', 'TRUE'),
(137, 'Serum Calcium', '11', '9', '', '', '', '', 'mg/dl', '', '', 'TRUE', 'TRUE'),
(138, 'Serum Chlorides', '106', '95', '', '', '', '', 'mEq/L', '', '', 'TRUE', 'TRUE'),
(139, 'Serum Cholestrol', '250', '150', '250', '150', '250', '150', 'mg%', 'Enzymetic', '', 'TRUE', 'TRUE'),
(140, 'Serum CK - NAC', '195', '25', '170', '24', '', '', 'U/L', '', '', 'TRUE', 'FALSE'),
(141, 'Serum Ck -MB', '20', '0', '', '', '', '', 'U/L', '', '', 'TRUE', 'FALSE'),
(142, 'Serum Creatinine', '1.7', '0.7', '1.7', '0.7', '1.7', '0.7', 'mg%', '', '', 'TRUE', 'TRUE'),
(143, 'Serum HDL Cholesterol', '60', '30', '70', '40', '', '', 'mg%', '', '', 'TRUE', 'TRUE'),
(144, 'Serum L.D.H.', '240', '70', '', '', '', '', 'I.U.', '', '', 'TRUE', 'FALSE'),
(145, 'Serum LDL Cholesterol', '150', '85', '150', '85', '150', '85', 'mg%', '', '', 'TRUE', 'FALSE'),
(146, 'Serum Potassium', '5.6', '3.8', '', '', '', '', 'mEq/L', '', '', 'TRUE', 'TRUE'),
(147, 'Serum Sodium', '148', '133', '', '', '', '', 'mEq/L', '', '', 'TRUE', 'TRUE'),
(148, 'Serum Triglycerides', '160', '60', '160', '60', '160', '60', 'mg%', '', '', 'TRUE', 'TRUE'),
(149, 'Serum Uric Acid', '7', '2', '7', '2', '7', '2', 'mg%', '', '', 'TRUE', 'TRUE'),
(150, 'Serum VLDL', '35', '5', '35', '5', '35', '5', 'mg%', '', '', 'TRUE', 'TRUE'),
(151, 'Sp. gravity', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(152, 'Specimen', '', '', '', '', '', '', '', '', 'Morning', 'FALSE', 'FALSE'),
(153, 'Sperm Count', '', '', '', '', '', '', 'millions/cu mm', '', '', 'TRUE', 'FALSE'),
(154, 'Stain Use', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(155, 'Sugar', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(156, 'Titer', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE'),
(157, 'Total', '12', '0.9', '', '', '', '', 'I.U.', '', '', 'TRUE', 'FALSE'),
(158, 'Total Cell Count', '', '', '', '', '', '', 'cu mm', '', '', 'TRUE', 'FALSE'),
(159, 'Total Chole. /HDL Chole. Ratio', '', '', '', '', '', '', 'mg%', '', '', 'TRUE', 'FALSE'),
(160, 'Total Protiens', '8', '6', '', '', '', '', 'gm / dL', '', '', 'TRUE', 'TRUE'),
(161, 'Undigested Food Particals', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(162, 'URINE GLUCOSE LEVEL', '', '', '', '', '', '', '', '', ':-', 'TRUE', 'FALSE'),
(163, 'Urine Sugar Fasting', '', '', '', '', '', '', '', 'Benedict''s', 'Absent', 'FALSE', 'TRUE'),
(164, 'Urine Sugar P.P', '', '', '', '', '', '', '', 'Benedict''s', 'Absent', 'FALSE', 'TRUE'),
(165, 'Urobilinogen', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(166, 'VDRL', '', '', '', '', '', '', '', 'Slide  Agglutination Method', 'Non Reactive', 'FALSE', 'TRUE'),
(167, 'Veg. forms of parasites', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(168, 'Vegetable cells', '', '', '', '', '', '', '', '', 'Absent', 'FALSE', 'FALSE'),
(169, 'W.B.C.Count', '10000', '5000', '10000', '5000', '10000', '5000', '/cu.mm', '', '', 'TRUE', 'FALSE'),
(170, 'Widal test', '', '', '', '', '', '', '', 'Rapid Slide Method', 'Negative', 'FALSE', 'TRUE'),
(171, 'Ziehl Neelson Stain', '', '', '', '', '', '', '', '', '', 'FALSE', 'FALSE');

-- --------------------------------------------------------

--
-- Table structure for table `registration`
--



CREATE TABLE IF NOT EXISTS registration (
  id serial,
  Regndate varchar(30) NOT NULL,
  P_Name varchar(100) NOT NULL,
  Gender varchar(30) NOT NULL,
  Age int NOT NULL,
  Doctor_name varchar(100) NOT NULL,
  Gross double precision NOT NULL,
  Concession double precision NOT NULL,
  DocCon double precision NOT NULL,
  ModePay varchar(100) NOT NULL,
  ChequeNo varchar(100) NOT NULL,
  Taxes double precision NOT NULL,
  Net double precision NOT NULL,
  Paid double precision NOT NULL,
  Balance double precision NOT NULL,
  ReportOn varchar(50) NOT NULL,
  ReportTime varchar(50) NOT NULL,
  ReportNote varchar(300) NOT NULL,
  Test_Details varchar(500) NOT NULL,
  PRIMARY KEY (id)
); 

--
-- Dumping data for table `registration`
--

INSERT INTO registration (id, Regndate, P_Name, Gender, Age, Doctor_name, Gross, Concession, DocCon, ModePay, ChequeNo, Taxes, Net, Paid, Balance, ReportOn, ReportTime, ReportNote, Test_Details) VALUES
(000001, '9/11/2001', 'MISS VAISHALI A. MORE', 'Female', 22, 'DR. H. D. PATIL     [M.B.B.S.]', 1070, 0, 0, 'Cash', '', 0, 1070, 0, 1070, '9/11/01', '6.00 pm', '', 'BIO, CBC, HIV, LIP, AUST AGEN, Profile Third, TEST'),
(000002, '9/11/2001', 'MISS ASMITA H. CHAUDHARI', 'Female', 23, 'DR. YASMEEN MEMON  [B.U.M.S. (PUNE)]', 1835, 0, 0, 'Cash', '', 0, 1835, 0, 1835, '9/11/01', '6.00 pm', '', 'LIP, BIO, Profile Two, Profile Third, Profile Four'),
(000003, '9/12/2001', 'MISS SANGEETA I. PANDEY', 'Female', 23, 'DR. S. S. JAIN  [M. F. A. M. (BOM)]', 24, 0, 0, 'Cash', '', 0, 24, 0, 24, '9/12/01', '6.00 pm', '', 'testing field test'),
(000004, '9/12/2001', 'B/O MRS. BEENA J. KALE', 'Baby', 30, 'DR. S. S. JAIN  [M. F. A. M. (BOM)]', 439, 0, 0, 'Cash', '', 0, 439, 400, 39, '9/12/01', '6.00 pm', '', 'testing field test, AUST AGEN, BIO, CBC, HIV'),
(000005, '9/12/2001', 'MISS VAIDAHI KULKARNI', 'Female', 34, 'DR. H. D. PATIL     [M.B.B.S.]', 64, 0, 0, 'Cash', '', 0, 64, 64, 0, '9/12/01', '6.00 pm', '', 'testing field test, CBC'),
(000006, '9/12/2001', 'MR.GANESH', 'Male', 30, 'DR. S. S. JAIN  [M. F. A. M. (BOM)]', 425, 10, 0, 'Cash', '', 0, 415, 0, 415, '9/12/01', '6.00 pm', '', 'CBC, BIO, AUST AGEN, HIV, LIP'),
(000007, '9/12/2001', 'MRS.GANESH', 'Female', 0, 'DR. H. D. PATIL     [M.B.B.S.]', 415, 0, 0, 'Cash', '', 0, 415, 0, 415, '9/12/01', '6.00 pm', '', 'CBC, BIO, AUST AGEN, HIV'),
(000008, '9/12/2001', 'MR.YOGEHS', 'Male', 23, 'DR. H. D. PATIL     [M.B.B.S.]', 425, 0, 0, 'Cash', '', 0, 425, 0, 425, '9/12/01', '6.00 pm', '', 'BIO, CBC, HIV, LIP, AUST AGEN'),
(000009, '9/12/2001', 'MR.Y', 'Male', 0, 'DR. B.J.CHOUDHARY  [M.B.B.S.(BOM)]', 115, 15, 0, 'Cash', '', 0, 100, 0, 100, '9/12/01', '6.00 pm', '', 'BIO, CBC');

-- --------------------------------------------------------

--
-- Table structure for table `reports`
--



CREATE TABLE IF NOT EXISTS reports (
  Id serial,
  Rcode varchar(10) NOT NULL,
  Report_Name varchar(200) NOT NULL,
  Sr int NOT NULL,
  Fields varchar(200) NOT NULL,
  Type varchar(10) NOT NULL,
  Amount double precision NOT NULL,
  Decided double precision NOT NULL,
  ChkNormal varchar(10) NOT NULL,
  ChkMethod varchar(100) NOT NULL,
  ChkImpression varchar(10) NOT NULL,
  chkinterpretation varchar(10) NOT NULL,
  Impression varchar(500) NOT NULL,
  Interpretation varchar(500) NOT NULL,
  PRIMARY KEY (Id)
);  

--
-- Dumping data for table `reports`
--

INSERT INTO reports (Id, Rcode, Report_Name, Sr, Fields, Type, Amount, Decided, ChkNormal, ChkMethod, ChkImpression, chkinterpretation, Impression, Interpretation) VALUES
(1, 'SRT', 'Stool Examination', 1, 'Stool Routine', 'Tests', 20, 20, 'False', 'False', 'False', 'False', '', ''),
(2, 'MAN', 'SKIN TEST', 1, 'Mantoux Test', 'Tests', 20, 20, 'False', 'True', 'False', 'True', '', '1. In children below 5 years , area of induration (transverse measurement mentioned first in report ) more than 10 mm are considered as positivern2. In adult and children above 5 years , area of induration (transverse measurement mentioned first in report) more than 15 mm is considered as Positivern3. Positive test indicate only sensitization to tuberculin and may not mean active tuberculosis.rnThe positive test could be due to primary/secondary infection (active/past) or even BCG innoculationrn'),
(3, 'SPH', 'SPECIAL HAEMATOLOGY TEST', 1, 'Platelet Count', 'Tests', 50, 150, 'True', 'False', 'False', 'False', '', ''),
(4, 'SPH', 'SPECIAL HAEMATOLOGY TEST', 2, 'Reticulocyte Count', 'Tests', 50, 150, 'True', 'False', 'False', 'False', '', ''),
(5, 'SPH', 'SPECIAL HAEMATOLOGY TEST', 3, 'Ab. Eosinophil Count', 'Tests', 50, 150, 'True', 'False', 'False', 'False', '', ''),
(6, 'BGR', 'BLOOD GROUP REPORT', 1, 'Blood Group', 'Tests', 30, 30, 'False', 'False', 'False', 'False', '', ''),
(7, 'WID', 'SEROLOGY REPORT', 1, 'Widal Test', 'Tests', 50, 50, 'False', 'True', 'False', 'True', '', '1. A titre above 1:80 should be considered as significantrn2. A rising titre (done each week) is considered to be definate evidance of infection, A single test result is considered of dignostic value when it is unusually high (above 160)rn3. A moderate simultanecous rise in the titre of ali ''H'' antigen suggests recent TAB vaccination .In the vaccinised patient a serological dignosis is usually made if there is four fold rise in 0 antigen titre if titre for 0 antigen is higher than 1:80 on a sing'),
(8, 'BOF', 'EXAMINATION OF BODY FLUIDS', 1, 'Body Fluid Test', 'Tests', 200, 200, 'False', 'False', 'False', 'False', '', ''),
(9, 'CMB', 'REPORT', 1, 'Coomb Test', 'Tests', 300, 800, 'False', 'False', 'False', 'False', '', ''),
(10, 'CMB', 'REPORT', 2, 'Rh - Antibody Titre', 'Tests', 250, 800, 'False', 'False', 'False', 'False', '', ''),
(11, 'CMB', 'REPORT', 3, 'ASO Titre', 'Tests', 200, 800, 'False', 'False', 'False', 'False', '', ''),
(12, 'CMB', 'REPORT', 4, 'C - Reactive Protien', 'Tests', 20, 800, 'False', 'False', 'False', 'False', '', ''),
(13, 'ELE', 'BIOCHEMISTRY REPORT (ELECTROLYTES)', 1, 'Serum Electrolytes', 'Tests', 200, 500, 'True', 'False', 'False', 'False', '', ''),
(14, 'LFT', 'LIVER FUNCTION TEST', 1, 'Serum Bilirubin', 'Tests', 80, 400, 'True', 'False', 'False', 'True', '', '* SERUM BILIRUBIN  For NEW BORN rnTOTAL BILIRUBIN  :- rnLess Than 3 Hours : Upto 12 mg %rnAfter    6 - 8 Hours : < 10 mg %   rnAfter 10 - 24 Hours: < 8 mg %'),
(15, 'LFT', 'LIVER FUNCTION TEST', 2, 'S.G.O.T', 'Tests', 60, 400, 'True', 'False', 'False', 'True', '', '* SERUM BILIRUBIN  For NEW BORN rnTOTAL BILIRUBIN  :- rnLess Than 3 Hours : Upto 12 mg %rnAfter    6 - 8 Hours : < 10 mg %   rnAfter 10 - 24 Hours: < 8 mg %'),
(16, 'LFT', 'LIVER FUNCTION TEST', 3, 'S.G.P.T', 'Tests', 60, 400, 'True', 'False', 'False', 'True', '', '* SERUM BILIRUBIN  For NEW BORN rnTOTAL BILIRUBIN  :- rnLess Than 3 Hours : Upto 12 mg %rnAfter    6 - 8 Hours : < 10 mg %   rnAfter 10 - 24 Hours: < 8 mg %'),
(17, 'LFT', 'LIVER FUNCTION TEST', 4, 'G.G.T.P.', 'Fields', 0, 400, 'True', 'False', 'False', 'True', '', '* SERUM BILIRUBIN  For NEW BORN rnTOTAL BILIRUBIN  :- rnLess Than 3 Hours : Upto 12 mg %rnAfter    6 - 8 Hours : < 10 mg %   rnAfter 10 - 24 Hours: < 8 mg %'),
(18, 'HAE', 'HAEMATOLOGY REPORT', 1, 'Haematology Test  1', 'Tests', 100, 250, 'True', 'False', 'True', 'False', 'CBC DONE ON SYSMAX KX 21 CELL COUNTER', ''),
(19, 'LFT', 'LIVER FUNCTION TEST', 5, 'Serum Alkaline Phosphatase', 'Tests', 75, 400, 'True', 'False', 'False', 'True', '', '* SERUM BILIRUBIN  For NEW BORN rnTOTAL BILIRUBIN  :- rnLess Than 3 Hours : Upto 12 mg %rnAfter    6 - 8 Hours : < 10 mg %   rnAfter 10 - 24 Hours: < 8 mg %'),
(20, 'LFT', 'LIVER FUNCTION TEST', 6, 'Total Proteins', 'Tests', 100, 400, 'True', 'False', 'False', 'True', '', '* SERUM BILIRUBIN  For NEW BORN rnTOTAL BILIRUBIN  :- rnLess Than 3 Hours : Upto 12 mg %rnAfter    6 - 8 Hours : < 10 mg %   rnAfter 10 - 24 Hours: < 8 mg %'),
(21, 'ELE', 'BIOCHEMISTRY REPORT (ELECTROLYTES)', 2, 'Serum Chlorides', 'Tests', 100, 500, 'True', 'False', 'False', 'False', '', ''),
(22, 'ELE', 'BIOCHEMISTRY REPORT (ELECTROLYTES)', 3, 'Serum Calcium', 'Tests', 100, 500, 'True', 'False', 'False', 'False', '', ''),
(23, 'ELE', 'BIOCHEMISTRY REPORT (ELECTROLYTES)', 4, 'Serum Phosphorus', 'Tests', 100, 500, 'True', 'False', 'False', 'False', '', ''),
(24, 'HIV', 'HIV Test', 1, 'HIV', 'Tests', 50, 50, 'False', 'True', 'True', 'True', 'If HIV test is " POSITIVE " has to be Confirmed by WESTERN BLOT Methid.', ''),
(25, 'SMA12', 'SMA 12', 1, 'Serum Total Proteins', 'Tests', 80, 1500, 'True', 'False', 'True', 'True', '', ''),
(26, 'SMA12', 'SMA 12', 2, 'Serum Calcium', 'Tests', 100, 1500, 'True', 'False', 'True', 'True', '', ''),
(27, 'SMA12', 'SMA 12', 3, 'Serum Phosphorus', 'Tests', 100, 1500, 'True', 'False', 'True', 'True', '', ''),
(28, 'SMA12', 'SMA 12', 4, 'Serum Cholesterol', 'Tests', 100, 1500, 'True', 'False', 'True', 'True', '', ''),
(29, 'SMA12', 'SMA 12', 5, 'Serum Creatine', 'Fields', 0, 1500, 'True', 'False', 'True', 'True', '', ''),
(30, 'SMA12', 'SMA 12', 6, 'Serum Uric Acid', 'Fields', 0, 1500, 'True', 'False', 'True', 'True', '', ''),
(31, 'SMA12', 'SMA 12', 7, 'Serum Bilirubin', 'Tests', 80, 1500, 'True', 'False', 'True', 'True', '', ''),
(32, 'SMA12', 'SMA 12', 8, 'Serum Alkaline Phosphatase', 'Tests', 75, 1500, 'True', 'False', 'True', 'True', '', ''),
(33, 'SMA12', 'SMA 12', 9, 'Serum CK - MB', 'Tests', 150, 1500, 'True', 'False', 'True', 'True', '', ''),
(34, 'SMA12', 'SMA 12', 10, 'Serum CK - NAC', 'Tests', 150, 1500, 'True', 'False', 'True', 'True', '', ''),
(35, 'SMA12', 'SMA 12', 11, 'Serum L.D.H', 'Tests', 150, 1500, 'True', 'False', 'True', 'True', '', ''),
(36, 'SMA12', 'SMA 12', 12, 'S.G.O.T', 'Tests', 60, 1500, 'True', 'False', 'True', 'True', '', ''),
(37, 'URT', 'Urine Examination Report', 1, 'Urine Routine', 'Tests', 40, 20, 'False', 'False', 'False', 'False', '', ''),
(38, 'CBC', 'BLOOD EXAMINATION REPORT', 1, 'CBC', 'Tests', 40, 40, 'True', 'False', 'True', 'False', 'CBC IS DONE ON SYSMAXKX 21 CELL COUNTER .rnrnMALARIA TEST IS DONE BY MALARIAL ANTIGEN METHOD', ''),
(39, 'SMA12', 'SMA 12', 13, 'S.G.P.T', 'Tests', 60, 1500, 'True', 'False', 'True', 'True', '', ''),
(40, 'LIP', 'LIPID PROFILE REPORT', 1, 'Serum Cholesterol', 'Tests', 100, 500, 'True', 'False', 'False', 'True', '', 'Serum Total Cholestrerol /HDL Cholestrol RatiornHDL Chelesterol value below 30mg% indicates increased risk for Ischemaic Heart Diseses . The clinical risk factor is better respected by the ratio of total Cholesterol to HDL Cholesterol in case of heart aliments.rnrn----------------------------------------------------------------------------------------------rnRisk                                 Total Cholestrol / HDL Cholestro   rnFactor                                 ( Female )       -        '),
(41, 'LIP', 'LIPID PROFILE REPORT', 2, 'Serum Triglycerides', 'Tests', 130, 500, 'True', 'False', 'False', 'True', '', 'Serum Total Cholestrerol /HDL Cholestrol RatiornHDL Chelesterol value below 30mg% indicates increased risk for Ischemaic Heart Diseses . The clinical risk factor is better respected by the ratio of total Cholesterol to HDL Cholesterol in case of heart aliments.rnrn----------------------------------------------------------------------------------------------rnRisk                                 Total Cholestrol / HDL Cholestro   rnFactor                                 ( Female )       -        '),
(42, 'LIP', 'LIPID PROFILE REPORT', 3, 'Serum HDL Cholestrol', 'Tests', 90, 500, 'True', 'False', 'False', 'True', '', 'Serum Total Cholestrerol /HDL Cholestrol RatiornHDL Chelesterol value below 30mg% indicates increased risk for Ischemaic Heart Diseses . The clinical risk factor is better respected by the ratio of total Cholesterol to HDL Cholesterol in case of heart aliments.rnrn----------------------------------------------------------------------------------------------rnRisk                                 Total Cholestrol / HDL Cholestro   rnFactor                                 ( Female )       -        '),
(43, 'LIP', 'LIPID PROFILE REPORT', 4, 'Serum LDL Colestrol', 'Tests', 100, 500, 'True', 'False', 'False', 'True', '', 'Serum Total Cholestrerol /HDL Cholestrol RatiornHDL Chelesterol value below 30mg% indicates increased risk for Ischemaic Heart Diseses . The clinical risk factor is better respected by the ratio of total Cholesterol to HDL Cholesterol in case of heart aliments.rnrn----------------------------------------------------------------------------------------------rnRisk                                 Total Cholestrol / HDL Cholestro   rnFactor                                 ( Female )       -        '),
(44, 'LIP', 'LIPID PROFILE REPORT', 5, 'Serum VLDL', 'Tests', 80, 500, 'True', 'False', 'False', 'True', '', 'Serum Total Cholestrerol /HDL Cholestrol RatiornHDL Chelesterol value below 30mg% indicates increased risk for Ischemaic Heart Diseses . The clinical risk factor is better respected by the ratio of total Cholesterol to HDL Cholesterol in case of heart aliments.rnrn----------------------------------------------------------------------------------------------rnRisk                                 Total Cholestrol / HDL Cholestro   rnFactor                                 ( Female )       -        '),
(45, 'LIP', 'LIPID PROFILE REPORT', 6, 'Total Chole. /HDL Chole. Ratio', 'Fields', 0, 500, 'True', 'False', 'False', 'True', '', 'Serum Total Cholestrerol /HDL Cholestrol RatiornHDL Chelesterol value below 30mg% indicates increased risk for Ischemaic Heart Diseses . The clinical risk factor is better respected by the ratio of total Cholesterol to HDL Cholesterol in case of heart aliments.rnrn----------------------------------------------------------------------------------------------rnRisk                                 Total Cholestrol / HDL Cholestro   rnFactor                                 ( Female )       -        '),
(46, 'AMY', 'BIOCHEMISTRY REPORT( ENZYME )', 1, 'Serum Amylase', 'Tests', 160, 760, 'True', 'False', 'False', 'False', '', ''),
(47, 'AMY', 'BIOCHEMISTRY REPORT( ENZYME )', 2, 'Serum Acid Phosphatase', 'Tests', 150, 760, 'True', 'False', 'False', 'False', '', ''),
(48, 'AMY', 'BIOCHEMISTRY REPORT( ENZYME )', 3, 'Serum L.D.H', 'Tests', 150, 760, 'True', 'False', 'False', 'False', '', ''),
(49, 'AMY', 'BIOCHEMISTRY REPORT( ENZYME )', 4, 'Serum CK - NAC', 'Tests', 150, 760, 'True', 'False', 'False', 'False', '', ''),
(50, 'AMY', 'BIOCHEMISTRY REPORT( ENZYME )', 5, 'Serum CK - MB', 'Tests', 150, 760, 'True', 'False', 'False', 'False', '', ''),
(51, 'COA', 'COAGULATION REPORT', 1, 'BTCT', 'Tests', 50, 60, 'True', 'False', 'False', 'False', '', ''),
(52, 'SEM', 'SEMAN EXAMINATION REPORT', 1, 'Semen Test', 'Tests', 50, 50, 'False', 'False', 'False', 'False', '', ''),
(53, 'BIO', 'BIOCHEMISTRY REPORT', 1, 'BIO', 'Tests', 75, 75, 'True', 'False', 'False', 'False', '', ''),
(54, 'ANC', 'BLOOD EXAMINATION REPORT', 1, 'Haemoglobin', 'Tests', 20, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', ''),
(55, 'AAG', 'SEROLOGY REPORT', 1, 'Serum Australia Antigen (HBsAg)', 'Fields', 0, 50, 'False', 'False', 'False', 'True', '', 'Heapatitis B surface antigen is universally accepted as a marker of Hepatitis B can be dianosed by detecting HBsAG in blood. Third generation tests with sensitivity of 10 ng /ml BHsAG in clinical laboratories. Above done test offers third generation specificity and sensitivity.rnIn certain casaes (less than 1% ) antigents like R.F. may give false positive results. False neagative results may be obtained by prozone effect. In suspected cases the serm is diluted 1:40 with normal saline.rnrnIn doub'),
(56, 'VDR', 'SEROLOGY REPORT', 1, 'VDRL', 'Tests', 50, 50, 'False', 'True', 'False', 'True', '', 'Although above test is fairly reliable for diagnosis of syphilis, in certain situations false positive and false neagative results may be obtained. Hence test has to be corelated with clinical findings.rnFalse Positive Reaction: Biological false positive (BEP) are reported in pneumococcal pneumonia , infective Hapattis, maleria, infectitious mononucleousis, autoimmune diases and in ageing individuals.rnFalse Neagative Reaction : (Patient has syphilis but the best is neagative) can be due to lowt'),
(57, 'PRG', 'PREGNANCY TEST', 1, 'Pregnancy Test', 'Tests', 100, 50, 'False', 'True', 'False', 'True', '', '1. Test is highly specific and sensitive hence positive result can be expected even 1-2 days before period is missedrnrn2. Due to high sensitivity this test can be used as screening test before prementural endometric biopsy is obtained in case of primary sterility.rnrn3. Due to same reasons positive result is expected in case incomplete abortionrnrn4. As this test detects HCG , positive result canbe obtained in neoplasm  secreting HCG (in absence of pregnacy).rnrn5. Tests that are positive , HCG'),
(58, 'RAT', 'SEROLOGY TEST', 1, 'R.A.Test', 'Tests', 50, 50, 'False', 'True', 'False', 'True', '', 'Because of delayed of rheumatoid factor,its more frequently present in chronicrnactive phase of the diseases than in early or chronic subclinical phases. Weak results may be confirmed by more sensetive tube methods. This test has occasionally been found positive in patients hepatities, sarcoidosis, cirrhosis of liver , syphilis , systematic lupus erythematosiss, hypergammabiobulinimia, sclerodera, siogren''s sydrome, ctutebateria and viral infections.rnIt is almost always absent in rhematic fever'),
(59, 'G6P', 'G 6 PD TEST', 1, 'G6PD', 'Tests', 50, 50, 'True', 'True', 'True', 'False', '', ''),
(60, 'ANC', 'BLOOD EXAMINATION REPORT', 2, 'PCV', 'Tests', 20, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', ''),
(61, 'ANC', 'BLOOD EXAMINATION REPORT', 3, 'Blood Sugar Fasting/Random', 'Tests', 30, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', ''),
(62, 'ANC', 'BLOOD EXAMINATION REPORT', 4, 'Blood Sugar PP/Random', 'Fields', 0, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', ''),
(63, 'ANC', 'BLOOD EXAMINATION REPORT', 5, 'Blood Group', 'Tests', 40, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', ''),
(64, 'ANC', 'BLOOD EXAMINATION REPORT', 6, 'VDRL', 'Tests', 50, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', ''),
(65, 'ANC', 'BLOOD EXAMINATION REPORT', 7, 'HIV', 'Tests', 200, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', ''),
(66, 'ANC', 'BLOOD EXAMINATION REPORT', 8, 'Serum Australia Antigen (HBsAg)', 'Tests', 50, 50, 'True', 'False', 'True', 'False', 'HIVTest is done by Tri - Dot method. and HBsAg is done by Immunochromatic Method. Positive HIV should be further confirmed by Western Blot Method', '');

-- --------------------------------------------------------

--
-- Table structure for table `tests`
--



CREATE TABLE IF NOT EXISTS tests (
  Id serial,
  Testname varchar(300) NOT NULL,
  Fieldname varchar(300) NOT NULL,
  Sr int NOT NULL,
  Amount double precision NOT NULL,
  PRIMARY KEY (Id)
);

--
-- Dumping data for table `tests`
--

INSERT INTO tests (Id, Testname, Fieldname, Sr, Amount) VALUES
(1, 'ASO Titre', 'ASO Titre', 1, 250),
(2, 'Ab. Eosinophil Count', 'Ab. Eosinophil Count', 1, 100),
(3, 'Serum Australia Antigen (HBsAg)', 'Serum Australia Antigen (HBsAg)', 1, 50),
(4, 'Blood Group', 'Blood Group', 1, 40),
(5, 'Haemoglobin', 'Haemoglobin', 1, 20),
(6, 'PCV', 'PCV', 1, 20),
(7, 'Blood Sugar Fasting/Random', 'Blood Sugar Fasting/Random', 1, 30),
(8, 'Widal Test', 'Widal test', 1, 50),
(9, 'Widal Test', 'Salmonella Typhi "O" Antigen', 2, 50),
(10, 'Widal Test', 'Salmonella Typhi "H" Antigen', 3, 50),
(11, 'Widal Test', 'Salmonella Typhi "A(H)" Antigen', 4, 50),
(12, 'C - Reactive Protien', 'C-Reactive Protein', 1, 20),
(13, 'Blood Group', 'Rh Factor', 2, 40),
(14, 'HIV', 'HIV', 1, 200),
(15, 'Rh - Antibody Titre', 'Rh - Antibody Titre', 1, 250),
(16, 'Widal Test', 'Salmonella Typhi "B(H)" Antigen', 5, 50),
(17, 'Serum Amylase', 'Serum Amylase', 1, 160),
(18, 'Serum L.D.H', 'Serum L.D.H.', 1, 150),
(19, 'Serum CK - NAC', 'Serum CK - NAC', 1, 150),
(20, 'Serum CK - MB', 'Serum Ck -MB', 1, 150),
(21, 'Serum Electrolytes', 'Serum Sodium', 1, 200),
(22, 'Serum Electrolytes', 'Serum Potassium', 2, 200),
(23, 'Serum Chlorides', 'Serum Chlorides', 1, 100),
(24, 'Serum Calcium', 'Serum Calcium', 1, 100),
(25, 'Serum Phosphorus', 'Serum  Inorganic Phosphorus', 1, 100),
(26, 'Platelet Count', 'Platelet Count', 1, 50),
(27, 'Reticulocyte Count', 'Reticulocyte Count', 1, 50),
(28, 'BTCT', 'Bleeding Time', 1, 150),
(29, 'BTCT', 'Clotting Time', 2, 150),
(30, 'Coomb Test', 'Direct Coombs Test', 1, 300),
(31, 'Coomb Test', 'Indirect Coombs Test', 2, 300),
(32, 'Stool Routine', 'GROSS EXAMINATION', 1, 50),
(33, 'CBC', 'Haemoglobin', 1, 50),
(34, 'Urine Routine', 'PHYSICAL EXAMINATION', 1, 40),
(35, 'Urine Routine', 'Quantity', 2, 40),
(36, 'Urine Routine', 'Colour', 3, 40),
(37, 'Urine Routine', 'Appearance', 4, 40),
(38, 'Urine Routine', 'Deposit', 5, 40),
(39, 'Haematology Test', 'Haemoglobin', 1, 100),
(40, 'Haematology Test', 'W.B.C.Count', 2, 100),
(41, 'Haematology Test', 'R.B.C Count', 3, 100),
(42, 'Haematology Test', 'P.C.V', 4, 100),
(43, 'Haematology Test', 'INDICES', 5, 100),
(44, 'Haematology Test', 'Mean Cell Count (MCV)', 6, 100),
(45, 'Haematology Test', 'Mean Cell Haemoglobin (MCH)', 7, 100),
(46, 'Urine Routine', 'Sp. gravity', 6, 40),
(47, 'Urine Routine', 'CHEMICAL EXAMINATION', 7, 40),
(48, 'Urine Routine', 'Reaction', 8, 40),
(49, 'Urine Routine', 'Sugar', 9, 40),
(50, 'Urine Routine', 'Albumin..', 10, 40),
(51, 'Urine Routine', 'Ketone', 11, 40),
(52, 'Urine Routine', 'Bile salt', 12, 40),
(53, 'BTCT', 'Prothrombin Time', 3, 150),
(54, 'BTCT', 'Control Prothrombin Time', 4, 150),
(55, 'BTCT', 'P. Index', 5, 150),
(56, 'Serum Bilirubin', 'Serum Bilirubin Total', 1, 80),
(57, 'Serum Bilirubin', 'Serum Bilirubin Direct', 2, 80),
(58, 'Serum Bilirubin', 'Serum Bilirubin Indirect', 3, 80),
(59, 'S.G.O.T', 'S.G.O.T.', 1, 60),
(60, 'S.G.P.T', 'S.G.P.T.', 1, 60),
(61, 'Serum Alkaline Phosphatase', 'Ser. Alkaline Phosphatase', 1, 75),
(62, 'Serum Total Proteins', 'Total Protiens', 1, 80),
(63, 'Serum Total Proteins', 'Albumin', 2, 80),
(64, 'Serum Total Proteins', 'Globulin', 3, 80),
(65, 'Serum Total Proteins', 'A/ G Ratio', 4, 80),
(66, 'Serum Cholesterol', 'Serum Cholestrol', 1, 100),
(67, 'Serum Triglycerides', 'Serum Triglycerides', 1, 130),
(68, 'Serum HDL Cholestrol', 'Serum HDL Cholesterol', 1, 90),
(69, 'Total Proteins', 'Total Protiens', 1, 100),
(70, 'Total Proteins', 'Albumin', 2, 100),
(71, 'Total Proteins', 'Globulin', 3, 100),
(72, 'Total Proteins', 'A/ G Ratio', 4, 100),
(73, 'Serum VLDL', 'Serum Vldl', 1, 80),
(74, 'Body Fluid Test', 'Quantity', 1, 200),
(75, 'Body Fluid Test', 'Colour', 2, 200),
(76, 'Body Fluid Test', 'Appearance', 3, 200),
(77, 'Body Fluid Test', 'Sediment', 4, 200),
(78, 'Body Fluid Test', 'Reaction', 5, 200),
(79, 'Body Fluid Test', 'Protein', 6, 200),
(80, 'Body Fluid Test', 'Glucose', 7, 200),
(81, 'Body Fluid Test', 'RBC', 8, 200),
(82, 'Body Fluid Test', 'Total Cell Count', 9, 200),
(83, 'Body Fluid Test', 'Neutrophils', 10, 200),
(84, 'Body Fluid Test', 'Lymphocytes', 11, 200),
(85, 'Body Fluid Test', 'Eosinophils', 12, 200),
(86, 'Body Fluid Test', 'Macrophages', 13, 200),
(87, 'Body Fluid Test', 'Other Cells', 14, 200),
(88, 'Body Fluid Test', 'Grain Stain', 15, 200),
(89, 'Body Fluid Test', 'Ziehl Neelson Stain', 16, 200),
(90, 'Body Fluid Test', 'Other Findings', 17, 200),
(91, 'Pregnancy Test', 'Pregnancy Test', 1, 50),
(92, 'Serum LDL Colestrol', 'Serum LDL Cholesterol', 1, 100),
(93, 'Semen Test', 'Quantity', 1, 50),
(94, 'Semen Test', 'Colour', 2, 50),
(95, 'Semen Test', 'Liquification', 3, 50),
(96, 'Mantoux Test', 'Mantoux Test', 1, 40),
(97, 'Mantoux Test', 'Area Of Induration', 2, 40),
(98, 'SMA 12', 'Serum  Inorganic Phosphorus', 1, 50),
(99, 'SMA 12', 'Serum Uric Acid', 2, 50),
(100, 'SMA 12', 'Serum Creatinine', 3, 50),
(101, 'SMA 12', 'Serum Bilirubin Total', 4, 50),
(102, 'SMA 12', 'Ser. Alkaline Phosphatase', 5, 50),
(103, 'SMA 12', 'Serum L.D.H.', 6, 50),
(104, 'SMA 12', 'S.G.O.T.', 7, 50),
(105, 'SMA 12', 'S.G.P.T.', 8, 50),
(106, 'SMA 12', 'Total Protiens', 9, 50),
(107, 'SMA 12', 'Serum Calcium', 10, 50),
(108, 'C.P.K', 'C.P.K', 1, 50),
(109, 'Stool Routine', 'Colour', 2, 50),
(110, 'Stool Routine', 'Consistancy', 3, 50),
(111, 'Stool Routine', 'Blood (Frank )', 4, 50),
(112, 'Stool Routine', 'Mucus', 5, 50),
(113, 'Stool Routine', 'Pus', 6, 50),
(114, 'Stool Routine', 'External Material Including Parasites', 7, 50),
(115, 'Stool Routine', 'pH', 8, 50),
(116, 'Stool Routine', 'MICROSCOPIC EXAMINATION', 9, 50),
(117, 'Stool Routine', 'Pus cells', 10, 50),
(118, 'Stool Routine', 'Red blood cells', 11, 50),
(119, 'Stool Routine', 'Macrophages', 12, 50),
(120, 'Stool Routine', 'Vegetable cells', 13, 50),
(121, 'Stool Routine', 'Undigested Food Particals', 14, 50),
(122, 'Stool Routine', 'Fat', 15, 50),
(123, 'Stool Routine', 'Veg. forms of parasites', 16, 50),
(124, 'Stool Routine', 'Amoeabae', 17, 50),
(125, 'Stool Routine', 'Flagellates', 18, 50),
(126, 'Stool Routine', 'Ova', 19, 50),
(127, 'Stool Routine', 'Cysts', 20, 50),
(128, 'Stool Routine', 'Occult blood', 21, 50),
(129, 'BIO', 'BLOOD GLUCOSE LEVEL', 1, 400),
(130, 'BIO', 'Blood Sugar fasting', 2, 400),
(131, 'BIO', 'Blood Sugar PP/Random', 3, 400),
(132, 'BIO', 'URINE GLUCOSE LEVEL', 4, 400),
(133, 'BIO', 'Urine Sugar Fasting', 5, 400),
(134, 'BIO', 'Urine Sugar P.P', 6, 400),
(135, 'BIO', 'Blood Urea', 7, 400),
(136, 'BIO', 'Blood Urea Nitrogen', 8, 400),
(137, 'BIO', 'Serum Creatinine', 9, 400),
(138, 'BIO', 'Serum Cholestrol', 10, 400),
(139, 'CBC', 'W.B.C.Count', 2, 50),
(140, 'CBC', 'R.B.C Count', 3, 50),
(141, 'CBC', 'P.C.V', 4, 50),
(142, 'Serum Acid Phosphatase', 'SERUM ACID PHOSPHATASE', 1, 50),
(143, 'Serum Acid Phosphatase', 'Total', 2, 50),
(144, 'Serum Acid Phosphatase', 'Prostratic', 3, 50),
(145, 'R.A.Test', 'R.A (Rheumatoid Arthitis) Test', 1, 50),
(146, 'VDRL', 'VDRL', 1, 50),
(147, 'VDRL', 'Titer', 2, 50),
(148, 'Stool Routine', 'Reducing subs', 22, 50),
(149, 'Stool Routine', 'Bacteria', 23, 50),
(150, 'Stool Routine', 'Others abnorms.', 24, 50),
(151, 'BIO', 'Serum Triglycerides', 11, 400),
(152, 'BIO', 'Serum Uric Acid', 12, 400),
(153, 'BIO', 'Serum Calcium', 13, 400),
(154, 'BIO', 'Serum  Inorganic Phosphorus', 14, 400),
(155, 'BIO', 'Serum Bilirubin Total', 15, 400),
(156, 'BIO', 'Serum Bilirubin Direct', 16, 400),
(157, 'BIO', 'Serum Bilirubin Indirect', 17, 400),
(158, 'BIO', 'S.G.O.T.', 18, 400),
(159, 'BIO', 'S.G.P.T.', 19, 400),
(160, 'BIO', 'Total Protiens', 20, 400),
(161, 'BIO', 'Albumin', 21, 400),
(162, 'BIO', 'Globulin', 22, 400),
(163, 'BIO', 'A/ G Ratio', 23, 400),
(164, 'BIO', 'Serum Amylase', 24, 400),
(165, 'BIO', 'Serum Potassium', 25, 400),
(166, 'G6PD', 'Dye Decolourisation Time', 1, 200),
(167, 'G6PD', 'G6PDH Activity', 2, 200),
(168, 'CBC', 'DIFFERENTIAL COUNT', 5, 50),
(169, 'CBC', 'Polymorphs', 6, 50),
(170, 'CBC', 'Lymphocyte', 7, 50),
(171, 'CBC', 'Eosinophils', 8, 50),
(172, 'CBC', 'Monocytes', 9, 50),
(173, 'CBC', 'Baseophils', 10, 50),
(174, 'CBC', 'Platelets', 11, 50),
(175, 'CBC', 'Morphology', 12, 50),
(176, 'CBC', 'Parasites', 13, 50),
(177, 'CBC', 'R.B.C. Morphology', 14, 50),
(178, 'CBC', 'Immature Cells', 15, 50),
(179, 'CBC', 'Morph. Abnorms Of W.B.C', 16, 50),
(180, 'CBC', 'E.S.R  1', 17, 50),
(181, 'Urine Routine', 'Bile pigment', 13, 40),
(182, 'Urine Routine', 'Urobilinogen', 14, 40),
(183, 'Urine Routine', 'MICROSCOPIC EXAMINATION', 15, 40),
(184, 'Urine Routine', 'Pus cells', 16, 40),
(185, 'Urine Routine', 'Epithelial cells', 17, 40),
(186, 'Semen Test', 'pH', 4, 50),
(187, 'Semen Test', 'Fructose Test', 5, 50),
(188, 'Urine Routine', 'Red blood cells', 18, 40),
(189, 'Urine Routine', 'Mucus threads', 19, 40),
(190, 'Urine Routine', 'Others abnorms.', 20, 40),
(191, 'Urine Routine', 'Casts', 21, 40),
(192, 'Urine Routine', 'Crystal', 22, 40),
(193, 'Urine Routine', 'Amorp. material', 23, 40),
(194, 'Urine Routine', 'Bacteria', 24, 40),
(195, 'Semen Test', 'Motility within one hour Active', 6, 50),
(196, 'Semen Test', 'Motility within one hour Sluggish', 7, 50),
(197, 'Semen Test', 'Motility within one hour Nonmobile', 8, 50),
(198, 'Semen Test', 'At end of three Active', 9, 50),
(199, 'Semen Test', 'At end of three Sluggish', 10, 50),
(200, 'Semen Test', 'At end of three Nonmotile', 11, 50),
(201, 'Semen Test', 'Morphology Normal', 12, 50),
(202, 'Semen Test', 'Morphology Abnormal', 13, 50),
(203, 'Semen Test', 'Sperm Count', 14, 50),
(204, 'Semen Test', 'Precursur Cells', 15, 50),
(205, 'Semen Test', 'Other Abnormalities PC', 16, 50),
(206, 'Semen Test', 'Other Abnormalities EC', 17, 50),
(207, 'Semen Test', 'Other Abnormalities RBC', 18, 50),
(208, 'Semen Test', 'Other Cells', 19, 50),
(209, 'Semen Test', 'Collection Time', 20, 50),
(210, 'Semen Test', 'Collection Method', 21, 50),
(211, 'Haematology Test', 'Mean Cell Haemoglobin Concentration(MCHC)', 8, 100),
(212, 'Haematology Test', 'DIFFERENTIAL COUNT', 9, 100),
(213, 'Haematology Test', 'Polymorphs', 10, 100),
(214, 'Haematology Test', 'Lymphocytes', 11, 100),
(215, 'Haematology Test', 'Eosinophils', 12, 100),
(216, 'Haematology Test', 'Monocytes', 13, 100),
(217, 'Haematology Test', 'Baseophils', 14, 100),
(218, 'Haematology Test', 'Platelets', 15, 100),
(219, 'Haematology Test', 'Morphology', 16, 100),
(220, 'Haematology Test', 'R.B.C. Morphology', 17, 100),
(221, 'Haematology Test', 'Immature Cells', 18, 100),
(222, 'Haematology Test', 'Morph. Abnorms Of W.B.C', 19, 100),
(223, 'Haematology Test', 'E.S.R  1', 20, 100),
(224, 'Haematology Test  1', 'Haemoglobin', 1, 100),
(225, 'Haematology Test  1', 'W.B.C.Count', 2, 100),
(226, 'Haematology Test  1', 'R.B.C Count', 3, 100),
(227, 'Haematology Test  1', 'P.C.V', 4, 100),
(228, 'Haematology Test  1', 'INDICES', 5, 100),
(229, 'Haematology Test  1', 'Mean Cell Count (MCV)', 6, 100),
(230, 'Haematology Test  1', 'Mean Cell Haemoglobin (MCH)', 7, 100),
(231, 'Haematology Test  1', 'Mean Cell Haemoglobin Concentration(MCHC)', 8, 100),
(232, 'Haematology Test  1', 'DIFFERENTIAL COUNT', 9, 100),
(233, 'Haematology Test  1', 'Polymorphs', 10, 100),
(234, 'Haematology Test  1', 'Lymphocytes', 11, 100),
(235, 'Haematology Test  1', 'Eosinophils', 12, 100),
(236, 'Haematology Test  1', 'Monocytes', 13, 100),
(237, 'Haematology Test  1', 'Baseophils', 14, 100),
(238, 'Haematology Test  1', 'Platelets', 15, 100),
(239, 'Haematology Test  1', 'Morphology', 16, 100),
(240, 'Haematology Test  1', 'R.B.C. Morphology', 17, 100),
(241, 'Haematology Test  1', 'Immature Cells', 18, 100),
(242, 'Haematology Test  1', 'Morph. Abnorms Of W.B.C', 19, 100),
(243, 'Haematology Test  1', 'E.S.R  1', 20, 100);